# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShoesPlease' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'SwiftSoup'
  pod 'AlertToast'	

  # Pods for ShoesPlease

end
