# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ShoesPlease' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'AlertToast'
  pod 'SwiftyJSON', '~> 5.0'	

  # Pods for ShoesPlease

end
